name: ShotokonokoDebug
main: io.github.highright1234.shotokonokodebug.ShotokonokoDebug
author: "HighRight"
version: 0.0.1
softdepend:
  - PlaceholderAPI
libraries:
  - io.github.highright1234:shotokonoko:0.0.9
#  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.4.0
#  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.4.0
#  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
  - io.github.monun:tap-core:4.7.2
  - io.github.monun:kommand-core:2.14.0
#  - io.github.monun:invfx-core:3.2.0